In [1]:
import numpy as np
import math
from dervar import *

def assoc(x, a):
    de = np.matmul(x,a)
    f = x - 1/(1 + de)
    return f

def derivs(x, a):
    de = np.matmul(x,a)
    # f1x1 f1x2 f1x3
    # f2x1 f2x2 f2x3
    f = x - 1/(1 + de)
    fx = 1/(1 + de)
    
    fx = np.reshape(fx, (5,))
    fx = fx**2
    result = (fx * a).transpose() + np.eye(5)
    
    return result

x = np.reshape(np.random.rand(5), (1,5))
a = np.array([[    0,     0, 1.213,     0, 3.134],
              [    0,     0, 0.369, 2.554,     0],
              [0.521, 2.547,     0,     0, 0.974],
              [    0, 1.410,     0,     0, 0.599],
              [1.255,     0, 1.051, 1.111,     0]])

oldf = assoc(x,a)
print("{:10s}".format("x in = "), x)
print("{:10s}".format("x out = "), 1/(1+np.matmul(x,a)))
print("x diff (f) = ", oldf)
print("dfdx is given by =")
print(derivs(x,a))

# print("changing x1")
# diff = 0.001*x[0,0]
# x[0,0] += diff
# newf = assoc(x,a)
# df = newf-oldf
# dfdx1 = df / diff
# print("oldf = ", oldf)
# print("newf = ", newf)
# print(dfdx1)

x in =     [[0.54630053 0.64335805 0.36681151 0.06334853 0.96301016]]
x out =    [[0.41672109 0.49417117 0.34338474 0.26932104 0.32182011]]
x diff (f) =  [[ 0.12957944  0.14918688  0.02342677 -0.20597251  0.64119005]]
dfdx is given by =
[[1.         0.         0.09047502 0.         0.21793887]
 [0.         1.         0.6219905  0.34432925 0.        ]
 [0.14302856 0.04350993 1.         0.         0.12392665]
 [0.         0.18525138 0.         1.         0.08058508]
 [0.32458268 0.         0.10087541 0.06203734 1.        ]]


In [9]:
f = assoc(x,a)
dfdx = derivs(x,a)
jtj = np.matmul(dfdx.transpose(), dfdx)
jtji = np.linalg.inv(jtj)
jm = np.matmul(jtji, dfdx.transpose())

print(dfdx)
print("x =  ", x)
dx = np.matmul(jm, f.transpose())
print("dx = ", dx)
x = x - dx.transpose()


[[1.         0.         0.20939897 0.         0.50440634]
 [0.         1.         0.32400305 0.17936565 0.        ]
 [0.25421553 0.0773335  1.         0.         0.22026424]
 [0.         0.5224989  0.         1.         0.22728907]
 [0.22847106 0.         0.07100537 0.04366757 1.        ]]
x =   [[0.63396956 0.35666466 0.45779458 0.45230589 0.27000145]]
dx =  [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
