In [1]:
import numpy as np
import math
from dervarnp import *
# from forward import *

def assoc(x, a):
    de = np.matmul(x,a)
    f = x - 1/(1 + de)
    return f

def derivs(x, a):
    de = np.matmul(x,a)
    # f1x1 f1x2 f1x3
    # f2x1 f2x2 f2x3
    f = x - 1/(1 + de)
    fx = 1/(1 + de)
    
    fx = np.reshape(fx, (5,))
    fx = fx**2
    result = (fx * a).transpose() + np.eye(5)
    
    return result

x = np.reshape(np.random.rand(5), (1,5))
a = np.array([[    0,     0, 1.213,     0, 3.134],
              [    0,     0, 0.369, 2.554,     0],
              [0.521, 2.547,     0,     0, 0.974],
              [    0, 1.410,     0,     0, 0.599],
              [1.255,     0, 1.051, 1.111,     0]])

oldf = assoc(x,a)
print("{:10s}".format("x in = "), x)
print("{:10s}".format("x out = "), 1/(1+np.matmul(x,a)))
print("x diff (f) = ", oldf)
print("dfdx is given by =")
print(derivs(x,a))

# print("changing x1")
# diff = 0.001*x[0,0]
# x[0,0] += diff
# newf = assoc(x,a)
# df = newf-oldf
# dfdx1 = df / diff
# print("oldf = ", oldf)
# print("newf = ", newf)
# print(dfdx1)

x in =     [[0.99075128 0.70808502 0.73968529 0.47936374 0.27693162]]
x out =    [[0.57705894 0.28090824 0.36309241 0.32091189 0.19559493]]
x diff (f) =  [[0.41369234 0.42717678 0.37659288 0.15845186 0.08133669]]
dfdx is given by =
[[1.         0.         0.17349145 0.         0.41791126]
 [0.         1.         0.20098234 0.11126231 0.        ]
 [0.15991719 0.04864752 1.         0.         0.13855974]
 [0.         0.26302226 0.         1.         0.11441571]
 [0.11989862 0.         0.03726269 0.02291617 1.        ]]


In [2]:
f = assoc(x,a)
dfdx = derivs(x,a)
jtj = np.matmul(dfdx.transpose(), dfdx)
jtji = np.linalg.inv(jtj)
jm = np.matmul(jtji, dfdx.transpose())

print(dfdx)
print("x =  ", x)
dx = np.matmul(jm, f.transpose())
print("dx = ", dx)
x = x - dx.transpose()


[[1.         0.         0.12752496 0.         0.30718583]
 [0.         1.         1.14858125 0.63584592 0.        ]
 [0.15282532 0.04649014 1.         0.         0.13241502]
 [0.         0.14296858 0.         1.         0.06219189]
 [0.35291774 0.         0.10968152 0.06745301 1.        ]]
x =   [[0.5717164  0.94209338 0.18124115 0.01951221 0.73850927]]
dx =  [[-0.0326624 ]
 [ 0.80884138]
 [-0.26833063]
 [-0.3618486 ]
 [ 0.46830191]]


In [4]:
from scipy import integrate
from dervarnp import *

In [18]:
x = np.linspace(0,1,257)
t = Var(0.1314)
y = integrate.romb(x**2/t, 1/257)
print(y.value, 1/3/0.1314)
print(derivative(y,t), 1/3 * ln(0.1314)) # DOES NOT WORK BECAUSE EACH ELEMENT IS ACCESSED
fx = lambda x: x**2/t
y = integrate.romberg(fx,0,1)
print(y.value, derivative(y,t))
t.children

2.5269126063326808 2.536783358701167
-19.2306895459108 -0.6765030576438755
2.5367833587011677 -19.30580942694952


[(-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.610e+00),
 (-57.91742828084857,   7.61

In [2]:
a = Var(0.12)
b = Var.sum(a,a,a,a)
print(derivative(b,a))

4.0


In [9]:
def trapzd_(func, a, b, s=0., N=1, args=()):
    '''
    Trapzd algorithm as according to Numerical Recipes in C (Second Edition)
    Chapter 4.2
    '''
    if N == 1: 
        return 0.5 * (b-a) * (func(a, *args)+func(b, *args))
    else:
        intv = 2**(N-1)
        tnm = intv
        dx = (b - a) / tnm
        x = a + 0.5*dx
        tot = [0] * intv
        for j in range(intv):
            tot[j] = func(x+j*dx, *args)
        s = (0.5 * (s + dx * Var.sum(*tot))) 
        return s
    
def qtrap(func, lower, upper, tol=1e-5, jmax=20, args=()):
    '''
    Wraps around trapzd_ to solve for a certain tolerance
    '''
    olds = 0
    for j in range(jmax):
        s = trapzd_(func, lower, upper, s=0., N=j+1, args=args)
        s += olds * 0.5
        if (j > 5): # Avoid early convergence
            if (abs(s-olds) < tol*abs(olds)) or (s == 0. and olds == 0.):
                return s
        olds = s
    raise Exception("qtrap algorithm stopped, maximum steps exceeded")    

def qsimp(func, lower, upper, tol=1e-5, jmax=20, args=()):
    '''
    qsimp algorithm follows Numerical Recipes in C (Second Edition)
    Chapter 4.2 where a wrapper is coded around trapzd_ and polint
    '''
    s, st, ost, os = (0., 0., 0., 0.)
    for j in range(jmax):
        st = trapzd_(func, lower, upper, s=0, N=j+1, args=args)
        s = (4.*st - ost)/3.
        if (j > 5):
            if (abs(s-os) < tol*abs(os)) or (s==0. and os==0.):
                print(j)
                return s
        os = s
        ost = st
    raise Exception("qsimp algorithm stopped, maximum steps exceeded")
    
def qromb(func, lower, upper, K=3, tol=1e-6, jmax=20, args=()):
    '''
    qromb algorithm follows Numerical Recipes in C (Second Edition)
    Chapter 4.3 where a wrapper is coded around trapzd_, and uses polint:
    the polynomial interpolation algorithm
    '''
    jmaxp = jmax+1
    s = [0] * jmaxp
    h = [0] * jmaxp
    h[0] = 1.
    for j in range(jmax):
        s[j] = trapzd_(func, lower, upper, s=s[j], N=j+1, args=args)
        if j >= K:
            ss, dss = polint(h[j-K+1:j+1], s[j-K+1:j+1], 0., get_dy=True)
            if abs(dss) < tol*abs(ss):
                return ss

        h[j+1] = 0.25*h[j]
        s[j+1] = s[j]

    raise Exception("qromb algorithm stopped, maximum steps exceeded")
    
def polint(xa, ya, x, get_dy=False):
    assert(isinstance(xa, list) and isinstance(ya, list))
    assert(len(xa) == len(ya))
    n = len(xa)

    dif = abs(x-xa[0])
    c = [0] * n
    d = [0] * n
    for i in range(n):
        dift = abs(x-xa[i])
        if dift <= dif:
            ns = i
            dif = dift
        c[i] = ya[i]
        d[i] = ya[i]
    # At this point we have the smallest difference to x located at ns, and 
    # c and d are duplicates of ya
    y = ya[ns] # initial guess of y located at ns
    ns -= 1
    for m in range(1,n):
        for i in range(0, n-m):
            ho = xa[i] - x
            hp = xa[i+m] - x
            w = c[i+1] - d[i]
            den = ho - hp
            if den == 0.: raise Exception("Poly_interp error")
            den = w/den
            d[i] = hp*den
            c[i] = ho*den
        if (2*ns+1) < (n-m):
            dy = c[ns+1]
        else:
            dy = d[ns]
            ns -= 1
        y += dy
    return (y,dy) if get_dy else y

def fx(x, a):
    y = x**2 -  x * exp(-a)
    return y

a = 0.5492
b = qromb(fx, 0, 2, args=(a,))
al = a - 0.001*a
bl = qsimp(fx, 0, 2, args=(al,))
au = a + 0.001*a
bu = qsimp(fx, 0, 2, args=(au,))
dbda = (bu-bl) / (au-al)
print(b, 2 * exp(-a), dbda)
a = Var(0.5492)
b = qromb(fx, 0, 2, tol= 1e-3,args=(a,))
print(b.value)
# for i in range(10):
#     c = abs(a)
#     b = trapzd_(fx, 0, 2, s=b, N=i+1, args=(a,))
# print(b.grad)
print(derivative(b, a))

6
6
1.511862545577998 1.1548231098039465 0.5774115839285664
1.5312880013071644
1.154823109803946


In [1]:
def rec(x):
    try:
        return rec(x+1)
    except:
        print(x)
rec(0)

2968


In [3]:
from dervarnp import *
import numpy as np


In [ ]:
a = np.array([1,2,3])
